baseURL = "http://samuelkillermann.com/"
languageCode = "en-us"
title = "sK"
theme= "hugo-paper"

[params]
author = "Sam Killermann"
description = "The curriculum vitae of Sam Killermann, comedian, author, and award-winning activist."

[build]
publish = "public"
command = "hugo"

[menu]

[[menu.main]]
identifier = "work"
name = "Work"
url = "/work/"
weight = -120

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = -110

[[menu.main]]
identifier = "now"
name = "Now"
url = "/now/"
weight = -100

[[menu.main]]
identifier = "bio"
name = "Bio"
url = "/bio/"
weight = -90

[[menu.main]]
identifier = "links"
url ="/links/"
name = "Links"
weight = -80


[context.production.environment]
HUGO_VERSION = "0.40.1"

[context.deploy-preview.environment]
HUGO_VERSION = "0.40.1"
