baseURL = "http://samuel-killermann.netlify.com/"
languageCode = "en-us"
title = "sK"
author = "Sam Killermann"
theme= "hugo-paper"

[build]
publish = "public"
command = "hugo"

[menu]

[[menu.main]]
identifier = "work"
name = "Work"
url = "/work/"
weight = -120

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = -110

[[menu.main]]
name = "Now"
url = "/now/"
weight = -100

[[menu.main]]
name = "Bio"
url = "/bio/"
weight = -90

[[menu.main]]
name = "Blog ↗"
url = "http://samkillermann.com"
weight = -70

[context.production.environment]
HUGO_VERSION = "0.40.1"

[context.deploy-preview.environment]
HUGO_VERSION = "0.40.1"
